name: Check Version Bump on PR

on:
  pull_request:
    branches:
      - main  

jobs:
  check_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Get PR Version
        id: pr_version
        run: |
          PR_VERSION=$(cat VERSION)
          echo "PR version: $PR_VERSION"
          echo "PR_VERSION=$PR_VERSION" >> $GITHUB_ENV

      - name: Get Main Branch Version
        id: main_version
        run: |
          git fetch origin main
          MAIN_VERSION=$(git show origin/main:VERSION)
          echo "Main version: $MAIN_VERSION"
          echo "MAIN_VERSION=$MAIN_VERSION" >> $GITHUB_ENV

      - name: Compare Versions
        run: |
          echo "Comparing PR version ($PR_VERSION) with main version ($MAIN_VERSION)..."
          if [ "$PR_VERSION" <= "$MAIN_VERSION" ]; then
            echo "ERROR: Version was not increased in VERSION file."
            exit 1
          fi

          echo "Version increased. Check Passed!"
